name: Continuous Integration

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    ci:
        runs-on: ubuntu-latest
        name: Continuous Integration
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Set up cargo cache
              uses: actions/cache@v4
              continue-on-error: false
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-cargo-
            - name: Install tooling
              run: |
                  rustup override set nightly
                  rustup component add rust-src
                  rustup component add rustfmt
                  rustup component add llvm-tools-preview
                  cargo install --list
                  cargo install --list | grep -q '^bootimage' || cargo install bootimage
            - name: Check formatting
              run: cargo fmt --check
            - name: Build kernel
              run: cargo build --release
            - name: Build bootimage
              run: cargo bootimage --release
            - name: Upload bootimage artifact
              uses: actions/upload-artifact@v4
              with:
                name: bootimage
                path: "target/x86_64-my_os/release/*.bin"